DROP TABLE IF EXISTS persons_family;
DROP TABLE IF EXISTS user_networks;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS families;
DROP TABLE IF EXISTS social_networks;
DROP TABLE IF EXISTS roles;

DROP TYPE IF EXISTS gender_enum;
DROP TYPE IF EXISTS family_role_enum;